# Generated by Django 2.2.17 on 2021-09-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bankMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='0', max_length=10, null=True)),
                ('amount', models.FloatField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('password', models.CharField(default='0', max_length=30)),
                ('email', models.EmailField(default='0', max_length=254)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('withdrawdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('balance', models.FloatField(default='0', max_length=30)),
                ('initial_balance', models.FloatField(default='0', max_length=30)),
                ('last_withdraw_amount', models.FloatField(default='0', max_length=30)),
                ('balance_in_gold', models.FloatField(default='0', max_length=30)),
                ('gold_price_at_creation', models.FloatField(default='0.0', max_length=30)),
                ('interest_balance', models.FloatField(default='0', max_length=30)),
                ('monthly_interest_balance', models.FloatField(default='0', max_length=30)),
                ('trigger', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='deposit_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('email', models.EmailField(default='0', max_length=254)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('password', models.CharField(default='0', max_length=30)),
                ('email', models.EmailField(default='0', max_length=254)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default='0', max_length=30)),
                ('return_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('return_amount', models.FloatField(default='0', max_length=30)),
                ('bank_profit', models.FloatField(default='0', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='priceOfGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='0', max_length=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gold_price', models.FloatField(default='0.0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('password', models.CharField(default='0', max_length=30)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('coin_type', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('price', models.FloatField(default='0', max_length=30)),
                ('coin_picture', models.ImageField(blank=True, upload_to='profiles_coin')),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('email', models.EmailField(default='0', max_length=254)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Mars', 'Mars')], default='', max_length=30, null=True)),
                ('mobileNo', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('account_age', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/profiles_pic/demo_profile_pic2.png', upload_to='profiles_pic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
