# Generated by Django 2.2.17 on 2020-12-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0006_auto_20201209_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='currentdate',
        ),
    ]
