# Generated by Django 2.2.17 on 2020-12-09 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0007_remove_userprofileinfo_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
