# Generated by Django 2.2.17 on 2020-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0010_auto_20201209_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='acct_no',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='balance',
            field=models.IntegerField(default='0'),
        ),
    ]
