# Generated by Django 2.2.17 on 2020-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0011_auto_20201209_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='acct_no',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='balance',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
