# Generated by Django 2.2.17 on 2020-12-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0012_auto_20201209_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_name',
        ),
    ]
