# Generated by Django 2.2.17 on 2020-12-09 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goldbankapp', '0013_remove_account_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='balance',
            new_name='acc_no',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='acct_no',
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='0', max_length=30)),
                ('last_name', models.CharField(default='0', max_length=30)),
                ('email', models.EmailField(default='0', max_length=254)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.CharField(default='0', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
