# Generated by Django 2.2.17 on 2020-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0014_auto_20201209_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='acc_no',
            new_name='accno',
        ),
    ]
