# Generated by Django 2.2.17 on 2020-12-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0015_auto_20201209_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='accno',
        ),
    ]
