# Generated by Django 2.2.17 on 2020-12-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0018_auto_20201209_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deposits',
            new_name='depositss',
        ),
    ]
