# Generated by Django 2.2.17 on 2020-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0019_auto_20201209_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='depositss',
            new_name='deposit',
        ),
    ]
