# Generated by Django 2.2.17 on 2020-12-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0024_auto_20201210_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
