# Generated by Django 2.2.17 on 2020-12-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0025_auto_20201210_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='username',
        ),
    ]
