# Generated by Django 2.2.17 on 2020-12-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0027_auto_20201210_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='password',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
