# Generated by Django 2.2.17 on 2020-12-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0028_deposit_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='balance',
        ),
    ]
