# Generated by Django 2.2.17 on 2020-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0029_remove_userprofileinfo_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default='0', max_length=100)),
            ],
        ),
    ]
