# Generated by Django 2.2.17 on 2020-12-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0031_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user',
            new_name='username',
        ),
    ]
