# Generated by Django 2.2.17 on 2020-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0032_auto_20201216_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='username1',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
