# Generated by Django 2.2.17 on 2020-12-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0035_remove_userprofileinfo_username1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='username',
            new_name='user',
        ),
    ]
