# Generated by Django 2.2.17 on 2020-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0038_remove_userprofileinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateField(default='0'),
        ),
    ]
