# Generated by Django 2.2.17 on 2020-12-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0039_userprofileinfo_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateTimeField(),
        ),
    ]
