# Generated by Django 2.2.17 on 2020-12-15 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0042_auto_20201216_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
