# Generated by Django 2.2.17 on 2020-12-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0043_auto_20201216_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth2',
            field=models.DateTimeField(),
        ),
    ]
