# Generated by Django 2.2.17 on 2020-12-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0049_auto_20201216_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='dateofbirth2',
        ),
    ]
