# Generated by Django 2.2.17 on 2020-12-15 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0050_remove_userprofileinfo_dateofbirth2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
    ]
