# Generated by Django 2.2.17 on 2020-12-15 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0053_auto_20201216_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
    ]
