# Generated by Django 2.2.17 on 2020-12-15 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0057_auto_20201216_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
