# Generated by Django 2.2.17 on 2020-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0062_auto_20201216_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateField(blank=True, default=0, null=True),
        ),
    ]
