# Generated by Django 2.2.17 on 2020-12-16 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0064_auto_20201216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dateofbirth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
