# Generated by Django 2.2.17 on 2020-12-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0067_userprofileinfo_accno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='accNo',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='dateofbirth',
        ),
    ]
