# Generated by Django 2.2.17 on 2020-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0068_auto_20201216_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmoney',
            name='serial',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
