# Generated by Django 2.2.17 on 2020-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0069_bankmoney_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
