# Generated by Django 2.2.17 on 2020-12-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0070_auto_20201218_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.IntegerField(default='0'),
        ),
    ]
