# Generated by Django 2.2.17 on 2020-12-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0071_auto_20201218_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
