# Generated by Django 2.2.17 on 2020-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0072_auto_20201218_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
