# Generated by Django 2.2.17 on 2020-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0073_auto_20201218_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
