# Generated by Django 2.2.17 on 2020-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0074_auto_20201218_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.FloatField(default='0', max_length=100, null=True),
        ),
    ]
