# Generated by Django 2.2.17 on 2020-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0077_auto_20201218_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmoney',
            name='serial',
        ),
        migrations.AddField(
            model_name='bankmoney',
            name='roll',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
