# Generated by Django 2.2.17 on 2020-12-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0078_auto_20201218_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmoney',
            old_name='roll',
            new_name='serial',
        ),
    ]
