# Generated by Django 2.2.17 on 2020-12-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0080_auto_20201218_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='serial',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
