# Generated by Django 2.2.17 on 2020-12-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0082_bankmoney_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmoney',
            name='amount2',
            field=models.FloatField(default='0', max_length=100),
        ),
    ]
