# Generated by Django 2.2.17 on 2020-12-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0083_bankmoney_amount2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='amount2',
            field=models.FloatField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
