# Generated by Django 2.2.17 on 2020-12-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0085_auto_20201218_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmoney',
            name='amount2',
            field=models.FloatField(default='0', max_length=100, null=True),
        ),
    ]
