# Generated by Django 2.2.17 on 2020-12-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0088_auto_20201218_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankMoneynew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='0', max_length=10, null=True)),
                ('abc', models.CharField(default='0', max_length=10, null=True)),
                ('amount', models.FloatField(default='0', max_length=100, null=True)),
                ('amount2', models.FloatField(blank=True, default='0', max_length=100, null=True)),
            ],
        ),
    ]
