# Generated by Django 2.2.17 on 2020-12-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0089_bankmoneynew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bankMoneynew',
        ),
        migrations.RemoveField(
            model_name='bankmoney',
            name='abc',
        ),
        migrations.RemoveField(
            model_name='bankmoney',
            name='amount2',
        ),
        migrations.AlterField(
            model_name='bankmoney',
            name='amount',
            field=models.FloatField(default='0', max_length=100, null=True),
        ),
    ]
