# Generated by Django 2.2.17 on 2020-12-18 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0092_auto_20201218_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
