# Generated by Django 2.2.17 on 2020-12-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0094_auto_20201218_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceofgold',
            name='serial',
        ),
    ]
