# Generated by Django 2.2.17 on 2020-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0099_auto_20201218_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(default=0, null=True),
        ),
    ]
