# Generated by Django 2.2.17 on 2020-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0100_auto_20201218_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(null=True),
        ),
    ]
