# Generated by Django 2.2.17 on 2020-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0102_auto_20201218_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(default='11-11-1111'),
        ),
    ]
