# Generated by Django 2.2.17 on 2020-12-18 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0103_auto_20201218_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
