# Generated by Django 2.2.17 on 2020-12-18 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0104_auto_20201218_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 23, 37, 59, 660023)),
        ),
    ]
