# Generated by Django 2.2.17 on 2020-12-18 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0105_auto_20201218_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 17, 38, 17, 969602, tzinfo=utc)),
        ),
    ]
