# Generated by Django 2.2.17 on 2020-12-18 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0108_auto_20201218_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceofgold',
            name='serial',
        ),
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
