# Generated by Django 2.2.17 on 2020-12-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0110_priceofgold_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='goldval',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
