# Generated by Django 2.2.17 on 2020-12-18 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0111_auto_20201219_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceofgold',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='priceofgold',
            name='goldval',
            field=models.FloatField(default='0.0', max_length=30),
        ),
    ]
