# Generated by Django 2.2.17 on 2020-12-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0112_auto_20201219_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceofgold',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='priceofgold',
            old_name='goldval',
            new_name='gold_price',
        ),
    ]
