# Generated by Django 2.2.17 on 2020-12-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0113_auto_20201219_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='balance_in_gold',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
