# Generated by Django 2.2.17 on 2020-12-19 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0114_deposit_balance_in_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='withdrawdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
