# Generated by Django 2.2.17 on 2020-12-19 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0116_auto_20201219_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='withdrawdate',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
