# Generated by Django 2.2.17 on 2020-12-19 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0117_auto_20201219_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='withdrawdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
