# Generated by Django 2.2.17 on 2020-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0120_auto_20201219_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='withdrawdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
