# Generated by Django 2.2.17 on 2020-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0122_auto_20201219_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_amount',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
