# Generated by Django 2.2.17 on 2020-12-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0126_auto_20201220_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
