# Generated by Django 2.2.17 on 2020-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0127_auto_20201220_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs_Bazar', 'Coxs_Bazar'), ('Bogra', 'Tangail'), ('Tangail', 'Feni'), ('Mars', 'Mars')], default='Dhaka', max_length=2),
        ),
    ]
