# Generated by Django 2.2.17 on 2020-12-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0128_auto_20201220_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs_Bazar', 'Coxs_Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Mars', 'Mars')], default='Dhaka', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobileNo',
            field=models.IntegerField(default='0', max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
