# Generated by Django 2.2.17 on 2020-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0129_auto_20201220_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
