# Generated by Django 2.2.17 on 2020-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0132_auto_20201220_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobileNo',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
