# Generated by Django 2.2.17 on 2020-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0136_auto_20201220_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles_pic'),
        ),
    ]
