# Generated by Django 2.2.17 on 2020-12-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0137_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='demo_profile_pic.jpg', upload_to='profiles_pic'),
        ),
    ]
