# Generated by Django 2.2.17 on 2020-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0141_auto_20201223_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='account_age',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
