# Generated by Django 2.2.17 on 2020-12-25 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0144_auto_20201224_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=30)),
                ('password', models.CharField(default='0', max_length=30)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('coin_type', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('price', models.FloatField(default='0', max_length=30)),
            ],
        ),
    ]
