# Generated by Django 2.2.17 on 2020-12-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0145_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
