# Generated by Django 2.2.17 on 2020-12-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0146_auto_20201225_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
