# Generated by Django 2.2.17 on 2020-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0148_auto_20201225_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='acc_no',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
    ]
