# Generated by Django 2.2.17 on 2020-12-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0149_auto_20201225_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='acc_no',
        ),
    ]
