# Generated by Django 2.2.17 on 2020-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0150_remove_userprofileinfo_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='acc_no',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
    ]
