# Generated by Django 2.2.17 on 2020-12-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0151_userprofileinfo_acc_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='acc_no',
        ),
    ]
