# Generated by Django 2.2.17 on 2020-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0152_remove_userprofileinfo_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='coin_picture',
            field=models.ImageField(blank=True, upload_to='profiles_coin'),
        ),
    ]
