# Generated by Django 2.2.17 on 2020-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0153_products_coin_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='monthly_interest_balance',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
