# Generated by Django 2.2.17 on 2020-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0154_deposit_monthly_interest_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='trigger',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
