# Generated by Django 2.2.17 on 2020-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0155_userprofileinfo_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='trigger',
        ),
        migrations.AddField(
            model_name='deposit',
            name='trigger',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
