# Generated by Django 2.2.17 on 2020-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0158_auto_20201226_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='account_age',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
