# Generated by Django 2.2.17 on 2020-12-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0161_auto_20201227_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
    ]
