# Generated by Django 2.2.17 on 2020-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0163_deposit_history_withdraw_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
