# Generated by Django 2.2.17 on 2020-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0164_auto_20201228_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='username',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
