# Generated by Django 2.2.17 on 2021-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbankapp', '0165_auto_20201228_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='initial_balance',
            field=models.FloatField(default='0', max_length=30),
        ),
    ]
